repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: commitizen
        name: My commitizen check
        entry: cz
        args: ['check', '--commit-msg-file', '.git/COMMIT_EDITMSG']
        pass_filenames: false
        language: system
        stages: [commit-msg]
        require_serial: true
        fail_fast: true

      - id: ruff
        name: ruff
        entry: ruff check --fix capacho tests
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

      - id: ruff-format
        name: ruff-format
        entry: ruff format capacho tests
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true
