name: ci

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'VERSION'
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Setup Python (uv)
      run: | # from https://github.com/astral-sh/uv/issues/1386
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/0.1.39/uv-installer.sh | sh
        uv venv .venv
        echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
        mkdir -p $(pip cache dir)
    - name: Install dependencies
      run: |
        uv pip install lume
        lume -install
    - name: Lint
      run: lume -lint
    - name: Static Analysis
      run: lume -static-analysis
    - name: Tests
      run: lume -test
    - name: Check Installation (--no-binary)
      run: lume -check-no-binary-installation
  test-imports:
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest ]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install latest version of capacho from code (without other dependencies as lume)
        run: uv pip install -e .
      - name: Check imports
        run: python -c "from capacho import Container, register, register_callable, Interface, ImplementationConfig, import_modules"
