name: docs

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Setup Python (uv)
      run: | # from https://github.com/astral-sh/uv/issues/1386
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/0.1.39/uv-installer.sh | sh
        uv venv .venv
        echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
        mkdir -p $(pip cache dir)
    - name: Create Documentation
      run: |
        uv pip install lume
        lume -docs
    - name: Publish
      run: mkdocs gh-deploy --force
